{"domain": "pnas.org", "title": "Correction for Lavine et al., Distinct macrophage lineages contribute to disparate patterns of cardiac recovery and remodeling in the neonatal and adult heart", "author": [], "link": "http://www.pnas.org/content/early/2016/02/23/1602039113.extract", "date": ["February 29, 2016"], "mail": []}
{"domain": "pnas.org", "title": "Correction for Mesquita et al., Genome of Rhodnius prolixus, an insect vector of Chagas disease, reveals unique adaptations to hematophagy and parasite infection", "author": [], "link": "http://www.pnas.org/content/early/2016/02/23/1600205113.extract", "date": ["February 29, 2016"], "mail": []}
{"domain": "pnas.org", "title": "Material heterogeneity in cancellous bone promotes deformation recovery after mechanical failure", "author": ["Ashley M. Torres", "Jonathan B. Matheny", "Tony M. Keaveny", "David Taylor", "Clare M. Rimnac", "Christopher J. Hernandez"], "link": "http://www.pnas.org/content/early/2016/02/24/1520539113.abstract", "date": ["February 29, 2016"], "mail": ["cjh275@cornell.edu"]}
{"domain": "pnas.org", "title": "Pressure-induced superconductivity in a three-dimensional topological material ZrTe5", "author": ["Yonghui Zhou", "Juefei Wu", "Wei Ning", "Nana Li", "Yongping Du", "Xuliang Chen", "Ranran Zhang", "Zhenhua Chi", "Xuefei Wang", "Xiangde Zhu", "Pengchao Lu", "Cheng Ji", "Xiangang Wan", "Zhaorong Yang", "Jian Sun", "Wenge Yang", "Mingliang Tian", "Yuheng Zhang", "Ho-kwang Mao"], "link": "http://www.pnas.org/content/early/2016/02/23/1601262113.abstract", "date": ["February 29, 2016"], "mail": ["zryang@issp.ac.cn", "jiansun@nju.edu.cn", "yangwg@hpstar.ac.cn", "tianml@hmfl.ac.cn", "hmao@carnegiescience.edu"]}
{"domain": "pnas.org", "title": "Immunoproteasome deficiency is a feature of non-small cell lung cancer with a mesenchymal phenotype and is associated with a poor outcome", "author": ["Satyendra C. Tripathi", "Haley L. Peters", "Ayumu Taguchi", "Hiroyuki Katayama", "Hong Wang", "Amin Momin", "Mohit Kumar Jolly", "Muge Celiktas", "Jaime Rodriguez-Canales", "Hui Liu", "Carmen Behrens", "Ignacio I. Wistuba", "Eshel Ben-Jacob", "Herbert Levine", "Jeffrey J. Molldrem", "Samir M. Hanash", "Edwin J. Ostrin"], "link": "http://www.pnas.org/content/early/2016/02/25/1521812113.abstract", "date": ["February 29, 2016"], "mail": ["herbert.levine@rice.edu", "EJOstrin@mdanderson.org"]}
{"domain": "pnas.org", "title": "Paracrine Wnt/\u03b2-catenin signaling mediates proliferation of undifferentiated spermatogonia in the adult mouse testis", "author": ["Hinako M. Takase", "Roeland Nusse"], "link": "http://www.pnas.org/content/early/2016/02/23/1601461113.abstract", "date": ["February 29, 2016"], "mail": ["rnusse@stanford.edu"]}
{"domain": "pnas.org", "title": "Critical role for Epac1 in inflammatory pain controlled by GRK2-mediated phosphorylation of Epac1", "author": ["Pooja Singhmar", "XiaoJiao Huo", "Niels Eijkelkamp", "Susana Rojo Berciano", "Faiza Baameur", "Fang C. Mei", "Yingmin Zhu", "Xiaodong Cheng", "David Hawke", "Federico Mayor, Jr.", "Cristina Murga", "Cobi J. Heijnen", "Annemieke Kavelaars"], "link": "http://www.pnas.org/content/early/2016/02/25/1516036113.abstract", "date": ["February 29, 2016"], "mail": ["akavelaars@mdanderson.org"]}
{"domain": "pnas.org", "title": "Immunoproteasome deficiency is a feature of non-small cell lung cancer with a mesenchymal phenotype and is associated with a poor outcome", "author": ["Satyendra C. Tripathi", "Haley L. Peters", "Ayumu Taguchi", "Hiroyuki Katayama", "Hong Wang", "Amin Momin", "Mohit Kumar Jolly", "Muge Celiktas", "Jaime Rodriguez-Canales", "Hui Liu", "Carmen Behrens", "Ignacio I. Wistuba", "Eshel Ben-Jacob", "Herbert Levine", "Jeffrey J. Molldrem", "Samir M. Hanash", "Edwin J. Ostrin"], "link": "http://www.pnas.org/content/early/2016/02/25/1521812113.abstract", "date": ["February 29, 2016"], "mail": ["herbert.levine@rice.edu", "EJOstrin@mdanderson.org"]}
{"domain": "pnas.org", "title": "Critical role for Epac1 in inflammatory pain controlled by GRK2-mediated phosphorylation of Epac1", "author": ["Pooja Singhmar", "XiaoJiao Huo", "Niels Eijkelkamp", "Susana Rojo Berciano", "Faiza Baameur", "Fang C. Mei", "Yingmin Zhu", "Xiaodong Cheng", "David Hawke", "Federico Mayor, Jr.", "Cristina Murga", "Cobi J. Heijnen", "Annemieke Kavelaars"], "link": "http://www.pnas.org/content/early/2016/02/25/1516036113.abstract", "date": ["February 29, 2016"], "mail": ["akavelaars@mdanderson.org"]}
{"domain": "pnas.org", "title": "Two distinct cytokinesis pathways drive trypanosome cell division initiation from opposite cell ends", "author": ["Qing Zhou", "Jianhua Gu", "Zhao-Rong Lun", "Francisco J. Ayala", "Ziyin Li"], "link": "http://www.pnas.org/content/early/2016/02/25/1601596113.abstract", "date": ["February 29, 2016"], "mail": ["fjayala@uci.edu", "lsslzr@mail.sysu.edu.cn", "ziyin.li@uth.tmc.edu"]}
{"domain": "pnas.org", "title": "Importin-7 mediates memory consolidation through regulation of nuclear translocation of training-activated MAPK in Drosophila", "author": ["Qian Li", "Xuchen Zhang", "Wantong Hu", "Xitong Liang", "Fang Zhang", "Lianzhang Wang", "Zhong-Jian Liu", "Yi Zhong"], "link": "http://www.pnas.org/content/early/2016/02/25/1520401113.abstract", "date": ["February 29, 2016"], "mail": ["zhongyi@tsinghua.edu.cn"]}
{"domain": "pnas.org", "title": "Long-ranged contributions to solvation free energies from theory and short-ranged models", "author": ["Richard C. Remsing", "Shule Liu", "John D. Weeks"], "link": "http://www.pnas.org/content/early/2016/02/26/1521570113.abstract", "date": ["February 29, 2016"], "mail": ["jdw@umd.edu"]}
{"domain": "pnas.org", "title": "Risk assessment of radioisotope contamination for aquatic living resources in and around Japan", "author": ["Hiroshi Okamura", "Shiro Ikeda", "Takami Morita", "Shinto Eguchi"], "link": "http://www.pnas.org/content/early/2016/02/23/1519792113.abstract", "date": ["February 29, 2016"], "mail": ["okamura@fra.affrc.go.jp"]}
{"domain": "pnas.org", "title": "Partial connectivity increases cultural accumulation within groups", "author": ["Maxime Derex", "Robert Boyd"], "link": "http://www.pnas.org/content/early/2016/02/23/1518798113.abstract", "date": ["February 29, 2016"], "mail": ["maxime.derex@gmail.com"]}
{"domain": "pnas.org", "title": "Insights into global diatom distribution and diversity in the world\u2019s ocean", "author": ["Shruti Malviya", "Eleonora Scalco", "St\u00e9phane Audic", "Flora Vincent", "Alaguraj Veluchamy", "Julie Poulain", "Patrick Wincker", "Daniele Iudicone", "Colomban de Vargas", "Lucie Bittner", "Adriana Zingone", "Chris Bowler"], "link": "http://www.pnas.org/content/early/2016/02/25/1509523113.abstract", "date": ["February 29, 2016"], "mail": ["cbowler@biologie.ens.fr"]}
{"domain": "pnas.org", "title": "Reply to Cronin: Consistency between decision-making, gaze, and natural social behavior validates inferences on macaque social cognition", "author": ["Sebastien Ballesta", "Jean-Ren\u00e9 Duhamel"], "link": "http://www.pnas.org/content/early/2016/02/26/1600687113.extract", "date": ["February 29, 2016"], "mail": ["duhamel@isc.cnrs.fr"]}
{"domain": "pnas.org", "title": "Mitochondrial Hsp90 is a ligand-activated molecular chaperone coupling ATP binding to dimer closure through a coiled-coil intermediate", "author": ["Nuri Sung", "Jungsoon Lee", "Ji-Hyun Kim", "Changsoo Chang", "Andrzej Joachimiak", "Sukyeong Lee", "Francis T. F. Tsai"], "link": "http://www.pnas.org/content/early/2016/02/26/1516167113.abstract", "date": ["February 29, 2016"], "mail": ["slee@bcm.edu", "ftsai@bcm.edu"]}
{"domain": "pnas.org", "title": "Two distinct cytokinesis pathways drive trypanosome cell division initiation from opposite cell ends", "author": ["Qing Zhou", "Jianhua Gu", "Zhao-Rong Lun", "Francisco J. Ayala", "Ziyin Li"], "link": "http://www.pnas.org/content/early/2016/02/25/1601596113.abstract", "date": ["February 29, 2016"], "mail": ["fjayala@uci.edu", "lsslzr@mail.sysu.edu.cn", "ziyin.li@uth.tmc.edu"]}
{"domain": "pnas.org", "title": "Autoinhibition and relief mechanism by the proteolytic processing of Toll-like receptor 8", "author": ["Hiromi Tanji", "Umeharu Ohto", "Yuji Motoi", "Takuma Shibata", "Kensuke Miyake", "Toshiyuki Shimizu"], "link": "http://www.pnas.org/content/early/2016/02/26/1516000113.abstract", "date": ["February 29, 2016"], "mail": ["shimizu@mol.f.u-tokyo.ac.jp"]}
{"domain": "pnas.org", "title": "Composite lithium metal anode by melt infusion of lithium into a 3D conducting scaffold with lithiophilic coating", "author": ["Zheng Liang", "Dingchang Lin", "Jie Zhao", "Zhenda Lu", "Yayuan Liu", "Chong Liu", "Yingying Lu", "Haotian Wang", "Kai Yan", "Xinyong Tao", "Yi Cui"], "link": "http://www.pnas.org/content/early/2016/02/26/1518188113.abstract", "date": ["February 29, 2016"], "mail": ["yicui@stanford.edu"]}
